### ISSUE TITLE
Publish a vocabulary/ontology at a stable URL

### ISSUE THREAD

**Issue by MarinaMartin** [project-open-data/project-open-data.github.io#136]
For "pod" namespace, once final 1.0 schema proposed in #44 is accepted:

pod:systemOfRecords
pod:webService
pod:accessLevel
pod:accessLevelComment
pod:primaryITInvestmentUII
pod:bureauCode
pod:programOffice
pod:dataQuality

Based on #44, am I missing anything?

**Comment by gbinal** [comment]
I think we're good and this issue can be closed.
