### ISSUE TITLE
Clarify and consolidate ISO 8601 documentation in the schema

### ISSUE THREAD

**Issue by philipashlock** [project-open-data/project-open-data.github.io#153]
ISO 8601 formatted dates are used for several fields (issued, modified, temporal) but the description and examples of ISO 8601 is somewhat inconsistent. Granted, this is in part because ISO 8601 allows for a wide degree of flexibility in how it's used - both in terms of precision and time zones. I would recommend that we consolidate a description of ISO 8601 usage and give it it's own paragraph (perhaps under Rationale for Metadata Nomenclature) and use a named anchor to link to it in the descriptions for issued, modified, temporal. 

I think it's also worth suggesting/encouraging a more specific use of ISO 8601, such as a full datetime down to the second in UTC like the example shown for the 'temporal' field. At the very least it would be good to format all example ISO 8601 dates the same way. I tend to prefer a date with all zeros for hours, minutes, seconds to one without hours, minutes, seconds at all. This is technically less accurate while being more precise since it could be interpreted as citing a specific time rather than citing known ambiguity (a zero rather than null) but I think the distinction is pretty obvious when you see a date with the time fields zero'ed out and I think the extra consistency is worth the slight pseudo accuracy.

**Comment by gbinal** [comment]
I think this is at a good place to close.
