### ISSUE TITLE
Need a mapping to ISO 11179

### ISSUE THREAD

**Issue by dsmorgan77** [project-open-data/project-open-data.github.io#181]
Need to add a mapping between project open data schema and ISO 11179 metadata registry standard.

**Comment by rebeccawilliams** [comment]
@dsmorgan77 -- agree with @mhogeweg that ISO 11179 is more relevant to catalogs infrastructure or perhaps informing DCAT vocabulary. Closing this here, but please re-open at github/gsa/Data.gov or here if there is a use case I am overlooking.
