### ISSUE TITLE
guidance on accessLevel needed

### ISSUE THREAD

**Issue by mhogeweg** [project-open-data/project-open-data.github.io#220]
The guidance at http://project-open-data.github.io/schema/ says that accessLevel should be one of “public”, “restricted public” or “non-public”.  But the metadata transformation guidance at http://project-open-data.github.io/metadata-resources/ says that accessLevel can be derived from free text metadata fileds.

anyone ideas on how to consolidate the guidance?

**Comment by rebeccawilliams** [comment]
This was addressed in the v1.1 updates: https://project-open-data.cio.gov/v1.1/metadata-resources/#field-mappings Feel free to re-open this issue or start a new one if the mapping notes are unclear.
