### ISSUE TITLE
validator error on references

### ISSUE THREAD

**Issue by pschweitzerusgsgov** [project-open-data/project-open-data.github.io#243]
Using http://project-open-data.github.io/json-validator/ I tried to validate the file http://mrdata.usgs.gov/catalog/data.json

I see exactly one error message,

```
The ‘[0].references’ property must be a/an ‘string’. The type of the property is ‘object’ :(
```

This makes no sense, because all of my "references" properties are arrays of strings, each of which contains a URL.

What am I missing?  Is there a limit to the size of the file that can be uploaded to that json validator?  Is there a limit to the number of datasets it may describe?

Peter

**Comment by jlberryhill** [comment]
+1
