### ISSUE TITLE
Tie in between OIRA (reginfo.gov) and data.gov

### ISSUE THREAD

**Issue by lilybradley** [project-open-data/project-open-data.github.io#256]
OMB has approved 9,199 currently active forms. Would be great to figure out the best way to get the reginfo.gov/public/do/PRA to interact with data.gov. Perhaps by including a meta data field for OMB control number for datasets?

Particularly compelling fields on reginfo.gov include: 
- OMB control number
- ICR reference number
- Agency/Subagency
- Title
- Abstract
- Authorizing statute**
- Federal Register 60 day and 30 day notices**
- ICR Summary of Burden (e.g., total annual responses requested)

Example: http://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=201308-0938-011

**Great stuff for understanding the connection between the legislative and executive branches and encouraging public engagement. For example, with the Federal Register notices, you can track public comments (e.g., who is commenting, who are interested parties). 

From the agency perspective, agencies that most often interact with the public (regulatory, grant, benefits) collect, and share data related to OMB controlled forms. At this time however, it's unlikely that the OMB control number is included with the data listing.

**Comment by justgrimes** [comment]
The OMB Control Number is an important identifier and a useful piece of information. I'd strongly recommend that it be included as an optional/if-applicable field in the next Project Open Data Metadata Schema (v 1.2). I wouldn't include the other suggested fields as they are a little superfluous. Other information can be found separately using the OMB Control Number via http://www.reginfo.gov/public/do/PRASearch or in bulk https://www.whitehouse.gov/omb/inforeg_xmlreports
