### ISSUE TITLE
Strategic Alignment

### ISSUE THREAD

**Issue by OwenAmbur** [project-open-data/project-open-data.github.io#276]
The metadata should include a repeatable element enabling the citation of the identifiers for each of the strategic objectives supported by the dataset, thereby enabling discovery of data based upon the reason(s) it exists.

Since section 10 of the GPRA Modernization Act (GPRAMA) requires agencies to publish their strategic and performance plans and reports in machine-readable format, identifiers should soon be available for all of the goals and objectives they contain.

It would be good for the Data.gov site to leverage those identifiers.

**Comment by rebeccawilliams** [comment]
I agree that `programCode` and `primaryITInvestmentUII` fulfill much of the goals of this issue already.

**Comment by rebeccawilliams** [comment]
Given the feedback that this field may unnecessarily bloat the schema, and may already be covered by already present fields, I am closing this issue at this time.
