### ISSUE TITLE
Customer Focus

### ISSUE THREAD

**Issue by OwenAmbur** [project-open-data/project-open-data.github.io#277]
The metadata should include a repeatable element for the naming of stakeholder groups to which the dataset applies and/or to whom it may be of interest.

Initially, the names assigned to the groups may constitute a folksonomy but, over time, it may be formalized as a commonly recognized taxonomy.

**Comment by rebeccawilliams** [comment]
I think users are emergent and a better approach to serving audiences would be a recommendation engine on Data.gov fueled by keywords and analytics: https://github.com/GSA/data.gov/issues/605

I agree `programCode` and `primaryITInvestmentUII` fulfill what USG *thinks* may be the most relevant audience as well.

**Comment by rebeccawilliams** [comment]
Given the feedback that this field may unnecessarily bloat the schema, and may already be covered by already present fields, I am closing this issue at this time.
