### ISSUE TITLE
Add in other data hubs 

### ISSUE THREAD

**Issue by gbinal** [project-open-data/project-open-data.github.io#311]
https://github.com/GSA/slash-developer-pages/blob/master/loose-slash-data-pages.md

**Comment by rebeccawilliams** [comment]
added everything except: 
* http://www.aviationweather.gov/data; seemed the same as the Hub landing page at: http://www.aviationweather.gov/adds/ (which I did add) 
* http://coastalscience.noaa.gov/about/centers/ccehbr (where is the data??)

in this PR: https://github.com/project-open-data/project-open-data.github.io/pull/504
