### ISSUE TITLE
Change SORN to allow a "no" response

### ISSUE THREAD

**Issue by BrendaCoblentz** [project-open-data/project-open-data.github.io#334]
The field that asks for the SORN indicates a yes or no answer, but is really looking for a URL.  I suggest that the edit allow a no answer so that anyone viewing it can see that it was not skipped or not answered.  It is an expanded field, but I personally would like to know for sure especially with all of the identity theft going on.  So, the edit should be either a URL or no.

**Comment by rebeccawilliams** [comment]
Since this is not required, and we clarified that URLs from the Federal Register would be used in the v1.1 update: https://project-open-data.cio.gov/v1.1/schema/#systemOfRecords I believe this issue can be closed.
