### ISSUE TITLE
What to do when IT won't even let you use GitHub

### ISSUE THREAD

**Issue by mikecharles** [project-open-data/project-open-data.github.io#346]
Not sure if this is the right venue for this issue, but I work under NOAA, and our IT won't even let me use GitHub. They claim GitHub is a Cloud Server Provider, and hence must go through accreditation before we can use it.

Are there any official policies on the use of GitHub in the federal government that I can piggy-back? For example documentation of security requirements met by GitHub, therefore making it an approved service, etc.?

**Comment by justgrimes** [comment]
We're going to go ahead and close this issue, but to clarify, all government staff and contractors (along with the public) should be able to create GitHub accounts and engage with this project by filing issues, comments, and pull requests. If restrictions exist at your agency that conflict with this, you should reach out to the Office of the Federal CIO at ofcio@omb.eop.gov to discuss this matter further.
