### ISSUE TITLE
Include 'audience' in updated schema

### ISSUE THREAD

**Issue by logantpowell** [project-open-data/project-open-data.github.io#349]
Here's my rational: I believe one use for metadata is as a means by which to narrow or reduce the search space when looking for data pertinent to my use case. I believe that the type of user I am is - often - the first way by which many organizations organize their data. For example, you go to Amazon for goods, Twitter for news / updates, Ace Hardware for ... you catch my drift.

This is all well and good for our use of the interwebs when their are a bunch of different organizations who cater to the needs of a specific segment of users. However, in this case - with open data - we are seeking to accommodate the needs of a variety of different types of users (developers, community leaders, congress and other government types, journalists, academics, small businesses / entrepreneurs, etc...). I believe this might be a good argument for including the ['audience'](https://schema.org/audience) variable into the schema.

Source: https://schema.org/Dataset

**Comment by rebeccawilliams** [comment]
I think this issue is repetitive of things brought up in #277. Closing this here.
