### ISSUE TITLE
add a section listing agency chief data officers

### ISSUE THREAD

**Issue by gbinal** [project-open-data/project-open-data.github.io#367]
* Dept. of Commerce: Position Announced, Not Yet Filled
* Dept. of Transportation: Dan Morgan
  * Dept. of the Treasury, Office of Financial Research: Linda Powell
* General Services Administration: Kris Rowley 
* Federal Reserve Board: Micheline Casey

**Comment by rebeccawilliams** [comment]
This section has been added here: https://project-open-data.cio.gov/chief-data-officers/ 

Pull Requests for additions or relevant job postings are welcome!
