### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by benbalter** [project-open-data/project-open-data.github.io#420]
http://project-open-data.cio.gov/ appears to be down. The server doesn't return any response:

![screen shot 2015-01-04 at 4 56 36 pm](https://cloud.githubusercontent.com/assets/282759/5607685/adff1572-9432-11e4-8864-1d2312952492.png)

**Comment by NoahKunin** [comment]
Up now for me and for http://www.downforeveryoneorjustme.com/. Looks fixed @benbalter
