### ISSUE TITLE
Data.gov CSW issue?

### ISSUE THREAD

**Issue by mhogeweg** [project-open-data/project-open-data.github.io#421]
I'm trying to search Data.gov through the CSW service:
http://catalog.data.gov/csw-all?request=GetCapabilities&service=CSW&version=2.0.2

GetCapabilities replies fine, but a GetRecords request currently results in a 'Data.Gov - Akamai Error Page' as opposed to the CSW response. is there an update happening?

**Comment by kvuppala** [comment]
@mhogeweg 
Must have been a temp error now the GetRecords request works fine, getting the below response for the query http://catalog.data.gov/csw-all?service=CSW&version=2.0.2&request=GetRecords&typenames=csw:Record&elementsetname=brief

<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<csw:GetRecordsResponse xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inspire_common="http://inspire.ec.europa.eu/schemas/common/1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dct="http://purl.org/dc/terms/" xmlns:ows="http://www.opengis.net/ows" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:ogc="http://www.opengis.net/ogc" xmlns:fgdc="http://www.opengis.net/cat/csw/csdgm" xmlns:inspire_ds="http://inspire.ec.europa.eu/schemas/inspire_ds/1.0" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:os="http://a9.com/-/spec/opensearch/1.1/" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" version="2.0.2" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:SearchStatus timestamp="2015-01-09T11:57:38Z"/><csw:SearchResults nextRecord="11" numberOfRecordsMatched="1157537" numberOfRecordsReturned="10" recordSchema="http://www.opengis.net/cat/csw/2.0.2" elementSet="brief"/></csw:GetRecordsResponse>

**Comment by mhogeweg** [comment]
thanks. seems to be working again!
