### ISSUE TITLE
Open data core schema 1.1 web page does not load in Native IE9

### ISSUE THREAD

**Issue by bharathkannansba** [project-open-data/project-open-data.github.io#422]
The URL : https://project-open-data.cio.gov/v1.1/schema/ does not load completely in native IE9. Most of the federal agencies still run on native IE9 versions on Windows 7. It would be nice to have the webpage support this version

**Comment by konklone** [comment]
@bharathkannansba Could you provide a screenshot of the error?

**Comment by bharathkannansba** [comment]
The page is fully loading now. A day after I created the ticket, it started working.

Regards,
Bharath Kannan (Contractor)
OCIO - Senior Solution Architect
U.S. Small Business Administration
409 3rd St SW| Washington | DC | 20416
Work: 202.205.7004
Cell:240.678.2467
Email: bharathwaj.kannan@sba.gov

**Comment by rebeccawilliams** [comment]
Closing this issue for now, but please let us know if it happens again!
