### ISSUE TITLE
Create a link to "latest schema" page

### ISSUE THREAD

**Issue by DavidXPortnoy** [project-open-data/project-open-data.github.io#424]
I'd like to create a link to the POD metadata schema page from an external project.  Now https://project-open-data.cio.gov/schema/ indicates that the page has been deprecated in favor of https://project-open-data.cio.gov/v1.1/schema/.  Ideally, I wouldn't have to update the relevant link every time the schema version changes.  Would it make sense to always locate the latest schema in a URL that doesn't change?

**Comment by rebeccawilliams** [comment]
Thanks @DavidXPortnoy! I believe you can rely on /schema remaining a relevant permalink. 

The specific URL for v1.1 however is also included as a reference in [the schema](https://project-open-data.cio.gov/v1.1/schema/#conformsTo). 

I am not sure if the best path forward here is a redirect or to have /schema become a landing page that links to various versions of the schema. 

@philipashlock @gbinal thoughts here?

**Comment by gbinal** [comment]
Great points, though I think we're led by the desire to have the versions for the schema maintain reliable links and /schema/ is firmly established as the version 1.0.  I think we can always promise to have a prominent link to the current schema versions at the top of each page.

**Comment by gbinal** [comment]
Closing this for now but feel free to reopen or help us think through this more.
