### ISSUE TITLE
Add more helpful info to #7 templates for open data community events

### ISSUE THREAD

**Issue by leahbannon** [project-open-data/project-open-data.github.io#425]
[This page](https://project-open-data.cio.gov/engagement/#useful-resources-for-all-events) is very helpful, and as I talk to agencies, I find it needs:
* description/explanation of how to choose which event and why
* guidelines for running the data jam brainstorming sessions and data briefs, the datapalooza demos, and hackathon pitches

I'll work on this (I'd assign to myself if I could). If anyone from OSTP has resources that they could share, I'd be much obliged. cc @ErieMeyer @rypan @rjmajma

**Comment by rebeccawilliams** [comment]
Please! I definitely think more guidance on events would be helpful. 

These resources might be helpful too in providing some of the more practical "what you'll need to host an event" guidance:
* http://www.smartchicagocollaborative.org/civic-innovation-toolkit-how-to-run-a-civic-hackathon/
* http://transparencycamp.org/how-to/

Personally, I think the 'what event and why' guidance shouldn't be too heavy handed. I've seen folks get wrapped up in the titles of these templates, namely, being intimidated about 'hackathon' and I'd hate to see imaginations tempered. Truthfully, you Brainstorm, Celebrate, and Hack at all of these events. I'm happy to help on broader principles and what you need to prepare for different types of events.

**Comment by rebeccawilliams** [comment]
+ And more guides to engaging with stakeholders: https://medium.com/@elle_mccann/building-community-and-engagement-around-data-2fb7d72b13b4 cc @ElleMcCann

**Comment by rebeccawilliams** [comment]
* Add the 18F hackathons gh pages template: https://github.com/18f/hackathons

**Comment by rebeccawilliams** [comment]
* and this post on welcoming folks to Hackathons: https://18f.gsa.gov/2015/04/03/how-to-welcome-new-coders-to-a-civic-hackathon/

**Comment by rebeccawilliams** [comment]
Thanks for adding all of these guides in #400 @leahbannon. Please continue to add organizing resources!
