### ISSUE TITLE
Add Open Data Engagement & Prioritization Resources

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data.github.io#439]
The policy requires:

>c. Create a process to engage with customers to help facilitate and prioritize data release

>Agencies must create a process to engage with customers, through their www.[agency].gov/data pages and other necessary means, to solicit help in prioritizing the release of datasets and determining the most usable and appropriate formats for release. Agencies should make data available in multiple formats according to their customer needs. For example, high-volume datasets of interest to developers should be released using bulk downloads as well as Application Programming Interfaces (APIs). In addition, customer engagement efforts should help agencies prioritize efforts to improve the discoverability and usability of datasets that have already been released to the public but are not yet fully “open” (e.g., they are only available in closed, inaccessible formats). See Project Open Data for best practices and tools that can be used to implement customer engagement efforts.

In addition to expanding information on how to host live events (see #425), resources should be provided on: **(1) How to solicit feedback (including guidance on PRA)** and **(2) How to use Public Feedback to inform improvements to the discoverability and usability of datasets**.  

Below is a list to get us started. To accommodate these additions, I think §7 should break out into a numbered list, like sections: 2-6.

Public Feedback Resources
--------------------------------------------
* [Analyzing Who’s Using your Agency’s Data with FOIA requests](http://www.digitalgov.gov/2014/12/19/whos-using-your-agencys-data/) -- include this with note on FOIA Officers perhaps?
* Web Analytics - [Join DAP today](http://www.digitalgov.gov/services/dap)
* [US Public Participation Playbook](http://participation.usa.gov/)
* [Data.gov Data Request tool](https://github.com/GSA/data.gov/issues/422) [*forthcoming*]
* How to solicit feedback in relationship to The Paperwork Reduction Act:
    * [User Research and The Paperwork Reduction Act: How to Get it Done](http://www.digitalgov.gov/event/user-research-and-the-paperwork-reduction-act/) webinar, see the [video here](https://www.youtube.com/watch?v=_cqE4a8oAHU).
    * [Usability.gov's Guidance on PRA](http://www.usability.gov/how-to-and-tools/guidance/pra-overview.html)
    * + FAQ of often asked questions? What are they?

Prioritization Resources
----------------------------------------
* Framework examples:
  * [DOT's Model Data Inventory Approach](http://www.dot.gov/sites/dot.gov/files/docs/DOT%20-%20OpenData%20-%20Data%20Inventory%20Approach.pdf) - includes prioritization notes. 
 * [Montgomery County's internal and external dataset scoring - pg 41](http://montgomerycountymd.gov/open/Resources/Files/OpenDataImplementationPlan_FY14.pdf)
 * [Philadelphia's Cost/Demand analysis](http://cityofphiladelphia.github.io/slash-data/census/)
 * [New York City Open Data Plan](http://www.nyc.gov/html/doitt/downloads/pdf/nyc_open_data_plan.pdf) -- a citywide release plan, but the criteria for how individual agencies prioritized is not clear. 
 * + Open Data Deep Dive examples?
* Tools:
 * [Kickstart](https://github.com/project-open-data/kickstart)
 * [Azavea's Open Data Race](http://opendataphilly.org/contest/)
 * [Ideascale, e.g. Australia](https://datagovau.ideascale.com/)
 * [EPA Ideas for Apps](http://www.epa.gov/mygreenapps/ideas.html)

What else would be good?

**Comment by dsmorgan77** [comment]
New York State open data handbook: http://nys-its.github.io/open-data-handbook/guidelines.html?1423529327742

**Comment by shua123** [comment]
DataSF has done some great data inventory and guide work: http://datasf.org/blog/?page_id=48

**Comment by mheadd** [comment]
[opendata.guide](http://opendata.guide) has a section on prioritizing open data sets for release, as well as one on engaging with data users. 

http://opendata.guide/chapter2.html
http://opendata.guide/chapter8.html

The [Open Data Handbook](http://opendatahandbook.org/en/how-to-open-up-data/choose-datasets.html) also has a section on choosing datasets.

**Comment by stevage** [comment]
[Socrata's open data field guide](http://www.socrata.com/open-data-field-guide/)

**Comment by rebeccawilliams** [comment]
@stevage this chapter: http://www.socrata.com/open-data-field-guide-chapter/engage-your-community/ anything else?

**Comment by rebeccawilliams** [comment]
+ the new HHS http://demand-driven-open-data.github.io/ cc @DavidXPortnoy

**Comment by rebeccawilliams** [comment]
* the Data.gov CRM tools: 
 * http://www.data.gov/issue
 * http://www.data.gov/request

**Comment by philipashlock** [comment]
Here are some from the Civic Commons wiki (which is [being moved](https://github.com/CivComs/wiki) to GitHub)
* [Open Data Priorities](http://wiki.civiccommons.org/Open_Data_Priorities)
* [Risk Evaluation](http://wiki.civiccommons.org/Risk_Evaluation)

**Comment by rebeccawilliams** [comment]
More for *Smart Engagement*:
* Targeted Engagement Strategies: http://www.programmableweb.com/news/how-transparency-innovation-dogfooding-and-passion-drive-government-apis/analysis/2015/01/15
* Leveraging local civic hacker efforts: http://www.codeforamerica.org/blog/2014/12/23/2014-brigade-in-review/ 
* 'Help Wanted': http://www.codeforamerica.org/geeks/civicissues
* Citizen-Government Collaborative Problem-Solving: http://mindmixer.com/2015/01/what-we-hope-is-trending-in-2015/

I will consolidate, and make an attempt at a first pass for new Resources.

**Comment by rebeccawilliams** [comment]
All of these resources have been added with #549

**Comment by rebeccawilliams** [comment]
Reopening this until #549 is merged.
