### ISSUE TITLE
bureauCode and programCode as If-Applicable?

### ISSUE THREAD

**Issue by tomschenkjr** [project-open-data/project-open-data.github.io#445]
Because data.json is being used widely, including on all Socrata portals, that spread across municipal and state governments, does it make sense to require bureauCode and programCode as Always required in the documentation? Should it be changed to If-Applicable?

The impact is trivial, but semantically useful. In the case of Chicago, there will never be a bureauCode or programCode since it doesn't apply, breaking the recommendations of the format.

**Comment by rebeccawilliams** [comment]
Thanks @tomschenkjr! 

Right now the way that is distinguished in the metadata is with a small USG note: https://project-open-data.cio.gov/v1.1/schema/#USG-note See the discussion in #247.

I think changing the distinction to 'If-Applicable' might confuse federal implementers, but please share any ideas about how to make this more conspicuous.

**Comment by tomschenkjr** [comment]
Ah, ok, that makes sense. I didn't notice that in the table at the beginning.

Satisfies my question. Only suggestion would be to asterisk* those--tends to get me looking for a footnote.

**Comment by rebeccawilliams** [comment]
Closing for now since there is a notation, but feel free to reopen.
