### ISSUE TITLE
Provide documentation and examples on the use of redactions in JSON

### ISSUE THREAD

**Issue by philipashlock** [project-open-data/project-open-data.github.io#446]
The general guidance on redactions for federal agencies is as follows, but we need to provide examples of what this looks like as JSON. 

Redaction text       | Brief FOIA exemption description
-------              | -------
[[REDACTED-EX B3]]   | Specifically exempted from disclosure by statute (other than FOIA), provided that such statute (A) requires that the matters be withheld from the public in such a manner as to leave no discretion on the issue, or (B) establishes particular criteria for withholding or refers to particular types of matters to be withheld.
[[REDACTED-EX B4]]   | Trade secrets and commercial or financial information obtained from a person and privileged or confidential.
[[REDACTED-EX B5]]   | Inter-agency or intra-agency memorandums or letters which would not be available by law to a party other than an agency in litigation with the agency.
[[REDACTED-EX B6]]   | Personnel and medical files and similar files the disclosure of which would constitute a clearly unwarranted invasion of personal privacy.

**Comment by philipashlock** [comment]
This has started to be implemented with https://github.com/GSA/project-open-data-dashboard/issues/83 such that the following example below (taken from the existing [example](https://project-open-data.cio.gov/v1.1/metadata-resources/#sample-data-files)) would pass the schema validation 

Note that the particular exemption reason denoted by "B3" in the example used `[[REDACTED-EX B3]]` might not make sense in some of the places it's used in this example and more generally, the places where the redactions are used in this example might not make sense given the descriptions used in the other fields. The example here is just intended only to demonstrate what the redaction text would look like in the JSON syntax. 

It might not make sense to allow for redactions on all fields. For example it may be inappropriate or unnecessary to redact the following fields in full, though perhaps some of these could be partially redacted.

- `accessLevel`
- `rights`
- `bureauCode`
- `programCode`
- `identifier`
- `isPartOf`
- `systemOfRecords`

I can imagine it making sense to redact an entire `distribution` entry as demonstrated by the example here, but I'm not sure it would make sense to ever redact an entire `dataset`. At a minimum it seems like it may be necessary to include the `identifier` and `accessLevel` unredacted. 

```json
{
    "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
    "@id": "http://www.agency.gov/data.json",
    "@type": "dcat:Catalog",    
    "conformsTo": "https://project-open-data.cio.gov/v1.1/schema", 
    "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
    "dataset": [
        {
            "@type": "dcat:Dataset",
            "accessLevel": "non-public", 
            "accrualPeriodicity": "R/P1Y", 
            "bureauCode": [
                "018:10"
            ],
            "conformsTo": "http://www.agency.gov/widget-taxonomy/",
            "contactPoint": {
                "@type": "vcard:Contact",
                "fn": "Jane Doe", 
                "hasEmail": "mailto:jane.doe@agency.gov"
            }, 
            "describedBy": "http://www.agency.gov/datasets/widgets-dictionary.html", 
            "dataQuality": true, 
            "description": "This dataset provides national statistics on the production of widgets", 
            "distribution": [
                {
                    "@type": "dcat:Distribution",
                    "description": "[[REDACTED-EX B4]]", 
                    "downloadURL": "[[REDACTED-EX B4]]", 
                    "mediaType": "text/csv", 
                    "title": "[[REDACTED-EX B4]]"
                }, 
                "[[REDACTED-EX B4]]", 
                {
                    "@type": "dcat:Distribution",
                    "conformsTo": "http://www.agency.gov/widget-data-standard/", 
                    "description": "Widget data as a JSON feed", 
                    "downloadURL": "http://www.agency.gov/feeds/widgets-all.json", 
                    "format": "JSON", 
                    "mediaType": "application/json", 
                    "title": "widgets-all.json"
                }, 
                {
                    "@type": "dcat:Distribution",
                    "accessURL": "https://data.agency.gov/api/widgets-statistics/", 
                    "description": "A fully queryable REST API with JSON and XML output", 
                    "format": "API", 
                    "title": "Widgets REST API"
                }
            ], 
            "identifier": "http://dx.doi.org/10.7927/H4PZ56R2", 
            "issued": "2011-11-22", 
            "keyword": [
                "widget", 
                "manufacturing", 
                "factory"
            ], 
            "landingPage": "[[REDACTED-EX B4]]", 
            "language": [
                "en-US"
            ], 
            "license": "http://creativecommons.org/publicdomain/zero/1.0/", 
            "modified": "[[REDACTED-EX B4]]", 
            "primaryITInvestmentUII": "021-006227212", 
            "programCode": [
                "018:001"
            ], 
            "publisher": {
                "@type": "org:Organization",
                "name": "Widget Services", 
                "subOrganizationOf": {
                    "@type": "org:Organization",
                    "name": "Office of Citizen Services and Innovative Technologies"
                }
            }, 
            "references": [
                "http://agency.gov/docs/widgets-1.html", 
                "[[REDACTED-EX B4]]"
            ], 
            "rights": "This dataset has been given an international public domain dedication for worldwide reuse", 
            "spatial": "[[REDACTED-EX B4]]", 
            "systemOfRecords": "http://www.agency.gov/widgets/sorn/", 
            "temporal": "2009-09-01T12:00:00Z/2010-05-31T12:00:00Z", 
            "theme": [
                "manufacturing"
            ], 
            "title": "U.S. Widget Manufacturing Statistics"
        }, 
        {
            "@type": "dcat:Dataset",
            "accessLevel": "non-public", 
            "accrualPeriodicity": "R/P1Y", 
            "bureauCode": [
                "018:10"
            ], 
            "contactPoint": {
                "@type": "vcard:Contact",
                "fn": "James Doe", 
                "hasEmail": "mailto:james.doe@agency.gov"
            }, 
            "description": "This dataset provides ranges on widget phase modulation", 
            "identifier": "http://dx.doi.org/10.7927/H4K64G12", 
            "issued": "2011-11-22", 
            "keyword": "[[REDACTED-EX B4]]", 
            "landingPage": "http://agency.gov/widgets/data", 
            "language": [
                "en-US"
            ], 
            "license": "http://creativecommons.org/publicdomain/mark/1.0/", 
            "modified": "2011-11-19T12:00:00Z", 
            "primaryITInvestmentUII": "021-006227212", 
            "programCode": [
                "018:001"
            ], 
            "publisher": {
                "@type": "org:Organization",
                "name": "Widget Modulation Program", 
                "subOrganizationOf": {
                    "@type": "org:Organization",
                    "name": "Office of Citizen Services and Innovative Technologies", 
                    "subOrganizationOf": {
                        "@type": "org:Organization",
                        "name": "General Services Administration", 
                        "subOrganizationOf": {
                            "@type": "org:Organization",
                            "name": "U.S. Government"
                        }
                    }
                }
            }, 
            "references": [
                "http://agency.gov/docs/widgets-1.html", 
                "http://agency.gov/docs/widgets-2.html"
            ], 
            "rights": "This dataset is a U.S. Government Work and is not covered by copyright in the United States of America", 
            "spatial": "United States", 
            "systemOfRecords": "http://www.agency.gov/widgets/sorn/", 
            "temporal": "2009-09-01T12:00:00Z/2010-05-31T12:00:00Z",  
            "title": "U.S. Widget Phase Modulation Ranges"
        }, 
        {
            "@type": "dcat:Dataset",
            "accessLevel": "non-public", 
            "accrualPeriodicity": "R/P1Y", 
            "bureauCode": [
                "018:10"
            ], 
            "contactPoint": {
                "@type": "vcard:Contact",
                "fn": "[[REDACTED-EX B4]]", 
                "hasEmail": "[[REDACTED-EX B4]]"
            }, 
            "describedBy": "http://www.agency.gov/datasets/widget-modulation-dictionary.html", 
            "dataQuality": true, 
            "description": "This dataset provides ranges on widget phase modulators for 2011", 
            "distribution": [
                {
                    "@type": "dcat:Distribution",
                    "description": "Widget modulator data as a CSV file", 
                    "downloadURL": "[[REDACTED-EX B4]]", 
                    "format": "CSV", 
                    "mediaType": "text/csv", 
                    "title": "widgets.csv"
                }
            ], 
            "identifier": "http://dx.doi.org/10.7927/H49P2ZKM", 
            "isPartOf": "widget-modulators", 
            "issued": "2011-11-22", 
            "keyword": [
                "widget", 
                "modulation"
            ], 
            "landingPage": "http://agency.gov/widgets/data", 
            "language": [
                "en-US"
            ], 
            "license": "http://creativecommons.org/publicdomain/mark/1.0/", 
            "modified": "2011-11-19T12:00:00Z", 
            "primaryITInvestmentUII": "021-006227212", 
            "programCode": [
                "018:001"
            ], 
            "publisher": {
                "@type": "org:Organization",
                "name": "Widget Modulation Program", 
                "subOrganizationOf": {
                    "@type": "org:Organization",
                    "name": "Office of Citizen Services and Innovative Technologies", 
                    "subOrganizationOf": {
                        "@type": "org:Organization",
                        "name": "General Services Administration", 
                        "subOrganizationOf": {
                            "@type": "org:Organization",
                            "name": "U.S. Government"
                        }
                    }
                }
            }, 
            "references": [
                "http://agency.gov/docs/widgets-1.html", 
                "http://agency.gov/docs/widgets-2.html"
            ], 
            "rights": "This dataset is a U.S. Government Work and is not covered by copyright in the United States of America", 
            "spatial": "United States", 
            "systemOfRecords": "http://www.agency.gov/widgets/sorn/", 
            "temporal": "2009-09-01T12:00:00Z/2010-05-31T12:00:00Z", 
            "theme": [
                "manufacturing"
            ], 
            "title": "U.S. Widget Phase Modulation Ranges for 2011"
        }
    ]
}
```

**Comment by rebeccawilliams** [comment]
I think all fields should be redacted with a presumption of openness. This is inline with [the federal FOIA policy](http://www.justice.gov/sites/default/files/ag/legacy/2009/06/24/foia-memo-march2009.pdf). An example that reflects this would be useful too.

**Comment by rebeccawilliams** [comment]
Including the presumption of openness language (above) and DOT's PDL as a best practice would be good additions to this guidance as well.

**Comment by jlberryhill** [comment]
Thanks, guys, and great example @philipashlock. I'd also note that certain *parts* of a field can be redacted rather than the whole field, if only certain words are subject to FOIA exemption. Agree with @rebeccawilliams on the presumption of openness. Think agencies should not redact entire metadata records and that there may be some fields that would never make sense to be redacted.

**Comment by bpushed** [comment]
Greetings all -- As a foreign assistance agency, USAID is exempt from releasing data per the seven principled exceptions outlined in [OMB 12-01 (see Attachment 1, page 4)] (http://www.whitehouse.gov/sites/default/files/omb/bulletins/fy2012/b12-01.pdf).  

When we issued our [open data policy] (http://www.usaid.gov/sites/default/files/documents/1868/579.pdf), this is the guidance we provided to our staff for justifying exemptions.  Our FOIA office agrees that these do not conflict with the FOIA act, but I wanted to flag this issue so that we can adopt an approach that keeps both documents in mind.  Thanks.

**Comment by konklone** [comment]
@bpushed I believe that still means USAID needs to express those exemptions in the form of redacted JSON, with individualized determinations for each field and catalog entry.

**Comment by bpushed** [comment]
Thanks.  That is essentially our plan.  For the Sunlight Foundation FOIA request, we were asked specifically to use FOIA exemptions but would plan to revert to OMB 12-01 moving forward.

**Comment by bbrotsos** [comment]
We are only planning on redacting (if any) on the PDL and leaving the EDI with the full description.  This will increasingly become more difficult to manage without some additional metadata tags to automate generating PDL vs EDI.  However if you add additional metadata tags for redaction, the simplicity of the POD Schema would be lost.

Is there an equivalent way to do inline tags on text in a JSON fields like in xml?  For example:
```
    "description": "<Redacted type='exb4'>Non Public Title</> widgets data as a CSV file"
```
The only equivalent way I can think of to do this in json is:
```
   "description_redacted": "[[REDACTED-EX B4]] Non Public Title widgets data as a CSV file"   
   "description": "Non Public Title widgets data as a CSV file"
```   

This would needlessly complicate the schema.  Could Agencies submit both the PDL and EDI redacted?

**Comment by rebeccawilliams** [comment]
@bbrotsos Following up on this thread -- PDLs @ /data.json should include `non-public` datasets including any required redactions. If redactions are present, an unredacted copy must also be submitted to OMB Max. 

I think that was clear, but wanted to record that in this issue. Closing this issue as guidance is live: https://project-open-data.cio.gov/redactions/

New issues or pull requests to clarify that guidance are encouraged though.

**Comment by philipashlock** [comment]
@bbrotsos For what it's worth, this is what we're going to try for inventory.data.gov - https://github.com/GSA/enterprise-data-inventory/issues/182#issuecomment-128514823
