### ISSUE TITLE
Update CDO list

### ISSUE THREAD

**Issue by lukefretwell** [project-open-data/project-open-data.github.io#449]
Add:

Niall Brennan, CDO, Centers for Medicare and Medicaid Services
http://www.nextgov.com/big-data/2015/03/get-know-chief-data-officer-niall-brennan-cms/107748/

Brandon Pustejovsky, CDO, U.S. Agency for International Development
http://www.nextgov.com/big-data/2015/03/get-know-chief-data-officer-brandon-pustejovsky-usaid/107757/

Scott Shoup, CDO, Federal Emergency Management Agency
http://www.nextgov.com/big-data/2015/03/get-know-chief-data-officer-scott-shoup-fema/107760/

Ian Kalin, CDO, Commerce Department
http://www.nextgov.com/cio-briefing/wired-workplace/2015/03/commerce-department-joins-new-chief-data-officer-trend/107622/

**Comment by rebeccawilliams** [comment]
Note the pending: https://github.com/project-open-data/project-open-data.github.io/pull/451 -- I just added Brandon to that PR too, thanks! 

Right now the list is [the Department level](http://en.wikipedia.org/wiki/United_States_federal_executive_departments). @gbinal, thoughts on how to showcase sub-departmental agency CDOs?

**Comment by gbinal** [comment]
@rebeccawilliams - I don't think there's any compelling reason to keep it at that level.  It's helpful to highlight CDO's at agencies, too.  I'd say that if it's on [this list of federal agencies]http://en.wikipedia.org/wiki/List_of_federal_agencies_in_the_United_States(), it's worth being on our list

**Comment by rebeccawilliams** [comment]
Great, added the remainder in PR #460. Thanks @lukefretwell.
