### ISSUE TITLE
CC license urls https instead of http? 

### ISSUE THREAD

**Issue by tvol** [project-open-data/project-open-data.github.io#457]
on https://project-open-data.cio.gov/open-licenses/ does it matter that the CC license urls are still listed as http even though they now all get redirected to https?

**Comment by konklone** [comment]
@tvol I'm excited by the implication, but when I visit `http://creativecommons.org/publicdomain/zero/1.0/` I don't get redirected.

Same on `curl`:

```
$ curl --head http://creativecommons.org/publicdomain/zero/1.0/

HTTP/1.1 200 OK
Date: Fri, 03 Apr 2015 00:54:38 GMT
Server: Apache/2.4.7 (Ubuntu)
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-Varnish: 794046850 793986029
Age: 84
Via: 1.1 varnish-v4
Connection: keep-alive
```

**Comment by tvol** [comment]
@konklone ahh yes i realized i'm probably looking at it on chrome with https everywhere plugin which is probably trying to force it to https, no?

**Comment by konklone** [comment]
Probably so. And I've filed many a pull request in my life correcting the links from `http://` to `https://`. Save me from this burden and turn on the redirect server-side! :smiley_cat: (And maybe even get it into the [HSTS preload list](https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/)!)

**Comment by philipashlock** [comment]
This has been updated on the Project Open Data Site. When this is fully wired up on data.gov, we'll probably try to treat both synonymously
