### ISSUE TITLE
geospatial data preview appears broken

### ISSUE THREAD

**Issue by mhogeweg** [project-open-data/project-open-data.github.io#466]
I was trying to preview this dataset [Seward, Alaska 1 arc-second DEM](https://catalog.data.gov/dataset/seward-alaska-1-arc-second-dem), but [the preview](https://catalog.data.gov/dataset/seward-alaska-1-arc-second-dem/resource/973adcee-9248-4fa8-98c8-8ec5dfef0582) does not load.

Using the 'Open With > ArcGIS' option [does appear to work](http://www.arcgis.com/home/webmap/viewer.html?url=http://gis.ngdc.noaa.gov/arcgis/rest/services/dem_hillshades/ImageServer).

**Comment by rebeccawilliams** [comment]
Thanks @mhogeweg! I am closing this here, and opening an Issue at https://github.com/gsa/data.gov

**Comment by gbinal** [comment]
P.S.  Here's the link to the new issue - https://github.com/GSA/data.gov/issues/623

**Comment by mhogeweg** [comment]
thanks for following up.
