### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by mashume** [project-open-data/project-open-data.github.io#468]
There is a typo in the spelling of accessLevelComment in the "public" level data section:

Public: Data asset is or could be made publicly available to all without restrictions. The accesLevelComment field may be used to provide information on technical or resource barriers to increasing access to that data asset.

It should be spelled as accessLevelComment.

**Comment by rebeccawilliams** [comment]
Thanks @mashume #471 when merged will fix that!
