### ISSUE TITLE
href property for links in footnotes

### ISSUE THREAD

**Issue by mattmoehr** [project-open-data/project-open-data.github.io#480]
Hi,

None of the links in the footnotes have the href property set, so none of the links... link. Maybe that's on purpose?

I'm also getting "GET https://project-open-data.cio.gov/assets/css/bootstrap.css.map 404 (Not Found)" on this page, but the links in the main text work fine so I doubt the css has anything to do with the problem.

Cheers,
Matt

**Comment by rebeccawilliams** [comment]
Thanks @mattmoehr! #544 should resolve this.
