### ISSUE TITLE
Link to Open Data Prioritization Toolkit

### ISSUE THREAD

**Issue by gbinal** [project-open-data/project-open-data.github.io#507]
https://cio.gov/wp-content/uploads/filebase/cio_document_library/Open%20Data%20Prioritization%20Toolkit%20Summary.html

Perhaps as `3-8` on the [homepage](https://project-open-data.cio.gov/)?  

Any thoughts?

**Comment by rebeccawilliams** [comment]
Already added under Resources. Updated the link to the machine-readable version in #510

Thanks Gray and :+1: to the CIO Council for updating the format: https://medium.com/@ciodotgov/how-the-cio-council-made-our-open-data-prioritization-tool-kit-more-open-6c04ea15286c
