### ISSUE TITLE
typo in the published catalog.jsonld

### ISSUE THREAD

**Issue by ziodave** [project-open-data/project-open-data.github.io#508]
Hello,

In the catalog.jsonld file published here https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld, there a typo at line 20:

```json
"@id": "dcat:acessURL",
```

instead of

```json
"@id": "dcat:accessURL",
```

**Comment by rebeccawilliams** [comment]
Thank you flagging! Fixed in #509
