### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by boodough** [project-open-data/project-open-data.github.io#514]
There is a missing d in the second paragraph of the **License** section

>**License**
>
> The project is a public domain work and is not subject to domestic or international copyright 
> protection. See the license file for additional information.
>
> Members of the public and US government employees who wish to contribute are encourage**d** > to do so, but by contributing, dedicate their work to the public domain and waive all rights to their 
> contribution under the terms of the CC0 Public Domain Dedication.

**Comment by rebeccawilliams** [comment]
Fixed! Thank you.

Feel free to submit [an edit directly](https://github.com/project-open-data/project-open-data.github.io/edit/master/README.md) anytime too. =)
