### ISSUE TITLE
Version the schema

### ISSUE THREAD

**Issue by afeld** [project-open-data/project-open-data.github.io#526]
Since it's possible for the schema to change dramatically over time, it would be useful to version the JSON file. I'd suggest using a [semantically-versioned](http://semver.org/) `version` attribute in the object, though there are certainly other options.

Disclaimer: I don't know too much about this project so perhaps there is context I don't know about – just something that came to mind immediately.

**Comment by gbinal** [comment]
Hi @afeld.  I might be mis-understanding but search for `version` [on the metadata schema page](https://project-open-data.cio.gov/v1.1/schema/) and let me know if that doesn't address what you're getting after.

**Comment by afeld** [comment]
Hmm, yep, [`conformsTo`](https://project-open-data.cio.gov/v1.1/schema/#conformsTo) is what I was looking for. Now I wish I included the JSON URL I was looking at, since I can't remember what it was any more. I don't remember seeing it there, but very possible I overlooked it. Ah well!
