### ISSUE TITLE
IDC Guidance Updates (February 2016)

### ISSUE THREAD

**Issue by justgrimes** [project-open-data/project-open-data.github.io#539]
Below are the OMB February 2016 IDC requirements for Open Data: 

### Open Data Progress, Use, and Impact
**Status: Updated**

* Agencies will continue to be assessed on their Open Data Policy progress through the Project Open Data Dashboard available at: http://labs.data.gov/dashboard/offices.
* Agencies will continue to provide a public version of their Enterprise Data Inventory at
[agency].gov/data.json and include their data.json dataset with the title “Enterprise Data
Inventory.” If necessary, agencies will coordinate with their Freedom of Information Act (FOIA)
offices to redact specific metadata text for “non-public” datasets only if the text is subject to a
FOIA exemption. Agencies shall use the instructions provided by OMB at https://project-opendata.cio.gov/redactions/
to conduct these redactions. If redactions are present, Agencies must
submit a non-redacted Enterprise Data Inventory JSON file to OMB in the appropriate agency
folder here: https://community.max.gov/x/8YamK.
* Agencies will ensure that their customer engagement process includes a transparent two-way
feedback mechanism. A link to an e-mail address or form by itself is not sufficient. For examples of
sufficient tools, please see https://project-open-data.cio.gov/engagement.
* Agencies will continue to enrich their metadata by:
  * Ensuring all public domain and open license information is properly documented. See
more details at: https://project-open-data.cio.gov/open-licenses/.
  * Ensuring all public, restricted public, and non-public APIs are properly documented. See
more details at https://project-open-data.cio.gov/v1.1/api/.
  * Ensuring all appropriate data assets are grouped as collections. See more details at
https://project-open-data.cio.gov/v1.1/collections/.

#### Questions on Use and Impact

**Public Datasets Ranking** *Identify at least 3 datasets that are valuable to the public and rank them in order of value. Explain why these datasets are valuable and how they are being used (or how they might be used) by the public.*

**Internal Datasets Ranking** *Identify at least 3 datasets that are valuable to your own agency (or among other agencies) and rank them in order of value. Explain why these datasets are valuable and how they are being used (or how they might be used) by your agency or other agencies.*

#### Question on the Enterprise Data Inventory 

**To what extent is your agency’s Enterprise Data Inventory (EDI) complete?** Select one of the following options: 
* To a very great extent (>75%)
* To a great extent (50-75%)
* To some extent (25-50%)
* To a very little extent (<25%) 

**Completeness Steps** *What steps have you taken to ensure your Enterprise Data Inventory is
complete?*

#### Questions on Public Engagement
**Public Feedback Mechanisms** *Describe your two-way public feedback mechanisms.*

**Feedback Received** *Provide five examples from this quarter of feedback received and what action your agency took in response (e.g. data quality improvements, access to previously unavailable data, or additional data formats).*

#### Agency Points of Contact (relevant section)

Agencies need to report and update the contact person for the following responsibilities

* Primary Open Data Contact (ODP)
* ODP: Communicating Strategic Value
* ODP: Public Data Release
* ODP: Private/Public Applications and Services
* ODP: Scaling Best Practices
* ODP: Data Privacy and Confidentiality
* ODP: Security Risk Assessment
* Chief Data Officer (If applicable)

**Comment by waldoj** [comment]
:+1: Thanks for reproducing that here!

**Comment by digiphile** [comment]
+1 for posting it publicly online in HTML, too.
https://github.com/project-open-data/project-open-data.github.io/issues/539




On Tue, Jan 12, 2016 at 10:44 AM, Waldo Jaquith <notifications@github.com>
wrote:

> [image: :+1:] Thanks for reproducing that here!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/project-open-data/project-open-data.github.io/issues/539#issuecomment-170951524>
> .
>



-- 
Alexander B. Howard
Phone: 410.849.9808 | @digiphile <http://twitter.com/digiphile>
Social Media: http://j.mp/ContactABH

**Comment by justgrimes** [comment]
@waldoj @digiphile No problem. IDC questions should be posted on Project Open Data website as discussed in #493; We'll add this information to the site and then close this issue when this task is complete. Thanks for the feedback.

**Comment by rebeccawilliams** [comment]
This can be closed when #543 is merged.

**Comment by justgrimes** [comment]
Closing this issue since #543 was merged. IDC guidance will be posted directly going forward.
