### ISSUE TITLE
API basics page - 404s

### ISSUE THREAD

**Issue by DamonDavis** [project-open-data/project-open-data.github.io#560]
I'm getting 404s for Salesforce, Amazon, eBay, etc

https://project-open-data.cio.gov/api-basics/

**Comment by waldoj** [comment]
It looks like Kin Lane retroactive changed his URL slugs to eliminate duplicate hyphens. e.g.:

`http://apievangelist.com/2011/01/28/history-of-apis--salesforcecom/`
became
`http://apievangelist.com/2011/01/28/history-of-apis-salesforcecom/`

Fixing these will require replacing every `--` with a `-` in URLs that begin with `http://apievangelist.com/`.

Note, too, that his site supports HTTPS now, so the URLs can also be updated while making this change.
