### ISSUE TITLE
How to access DOL's employers information for H1bs and Green Cards?

### ISSUE THREAD

**Issue by DeriveLLC** [project-open-data/project-open-data.github.io#574]
Hello -

I wanted to access the API's for DOL's public records like Number of H1's and Green Cards filed along with what what approved and denied.

I dont need the records just the numbers. Something like this.

http://www.myvisajobs.com/Visa-Sponsor/Mindtree/360691.htm.

Is there a way to access this API? Any help in that direction will be highly appreciated.

Regards
 Dave

**Comment by dsmorgan77** [comment]
I think these are all PDFs of performance data from the DOL ETA https://www.foreignlaborcert.doleta.gov/performancedata.cfm. You could try contacting the team at http://developer.dol.gov/ to see if this stuff is on their roadmap.

**Comment by DeriveLLC** [comment]
Thank you

Thanks and Regards

[Derive2]<http://www.derivetalent.com/>

Direct: 480-704-4848
Mobile: 602-570-0142

[Description: Description: View my profile on LinkedIn]<http://www.linkedin.com/pub/dave-narania/1/b3b/680/>
