### ISSUE TITLE
Allow non-federal specification so that usg required field do not fail validation

### ISSUE THREAD

**Issue by dkinzer** [project-open-data/project-open-data.github.io#581]
In the case of a state office that wants to publish some open data using the project open data standard, the data.json will fail validation because bureauCode is a required field for federal agencies, but there is no way to flag that the dataset as  *not* being federal.

**Comment by rebeccawilliams** [comment]
the non-federal validator should correct for this: https://labs.data.gov/dashboard/validate if you have further issues, file an issue at https://github.com/project-open-data/project-open-data-dashboard/issues or email datagov@gsa.gov
