### ISSUE TITLE
Inventory.Data.Gov, Need Account, Listed Contact Unresponsive

### ISSUE THREAD

**Issue by markbrady999** [project-open-data/project-open-data.github.io#582]
I would like to use Inventory.Data.Gov to submit my agency's metadata.  To do this I need an account.  The link for setting up an account is not working.   The contact listed for help is not responding.  Does anyone know who I should be contacting who is still alive?

mark.brady@usdoj.gov

**Comment by rebeccawilliams** [comment]
email datagov@gsa.gov or reach out at https://www.data.gov/contact for issues like these
