### ISSUE TITLE
Dead link to Federal Program Inventory in 'programCode' usage Notes

### ISSUE THREAD

**Issue by akharris** [project-open-data/project-open-data.github.io#584]
The `programCode` usages notes in the  v1.1 schema links to a now-dead Federal Program Inventory link: http://goals.performance.gov/sites/default/files/images/FederalProgramInventory_FY13_MachineReadable_091613.xls

I am specifically looking for the `programCode`s for the Department of the Interior and found https://www.performance.gov/federalprograminventory. However their Interior Dept. section does not seem to have what I'm looking for.

Could someone find the new location for the Federal Program Inventory and update the docs? I will continue to look on my own but I'm posting this issue in hopes that someone else already knows.

Thanks!

**Comment by sniderna** [comment]
Similar to this issue, the PDF link for the list of Bureau Codes is broken; it links to http://www.whitehouse.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf 

It is technically located at https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf as a backup, but it would obviously be preferable to get this either located on the current whitehouse.gov site, or located locally on data.gov

**Comment by antognoli** [comment]
I am also looking for the Program and Bureau Codes, if anyone happens to find them. I found the archived one mentioned above but would like to find the currently maintained copy for our metadata records.

**Comment by philipashlock** [comment]
This should be fixed by #601
