### ISSUE TITLE
display latest quarterly milestone at the top

### ISSUE THREAD

**Issue by kvuppala** [project-open-data/project-open-data.github.io#597]
On the https://labs.data.gov/dashboard/offices, would it better to display the latest milestone at the top of listing, display the values in reverse chronological order.  

As the number of milestones increase over a period of time, the list will become large and from usability aspect of selecting a milestone will be better in the above approach.

**Comment by rebeccawilliams** [comment]
Closing this since it is related to the dashboard and not this website.
