### ISSUE TITLE
Unique Identifiers should probably be globally unique rather than only unique for an org

### ISSUE THREAD

**Issue by willpugh** [project-open-data/project-open-data.github.io#69]
Looking at the description for "identifier" and the guidance, the suggestions are to make the identifiers unique for an Agency or Catalog.

I think we should actually change the guidance to be globally unique.  This could be something as easy as adding agency name before the agency identifier, e.g. gov.hhs.aspe.1234567 instead of 1234567.  Or it could simply be a URI.

There is no guarantee that catalogs won't aggregate or pull from other catalogs (and it is probably even likely).  If this happens a single catalog could get two items from different agencies that have the same identifier.  

One solution to this would be to make it a function of the catalog to add something to these datasets to give them unique IDs.  The problem with this is that, the "uniqueness" is creating by an intermediate party (not the source of truth).

So, now imagine that I setup a catalog that is going to aggregate a lot of health data. I pull from New York State's catalog, as well as a catalog from HHS.  I then get the exact same dataset (since HHS pulls from New York State's catalog un-beknownst to me), but it has two different identifiers in my system.  One is NY State's original ID.  The other is the ID that HHS's catalog had to create for me (to make sure it was unique within their catalog)

Seems like we could protect ourselves from a lot of identification problems down the line if we ask for global uniqueness for identifiers.

I would also suggest that as guidance, if an Agency already has an agency unique identifier, they should probably make it unique by appending their agency to it (rather than using something opaque like UUID).

**Comment by gbinal** [comment]
Agencies are strongly encouraged to do this in current guidance.  I think we can close this.
