### ISSUE TITLE
Data directories/metadata should identify copyright status of the data

### ISSUE THREAD

**Issue by JoshData** [project-open-data/project-open-data.github.io#8]
Agencies publishing data directories should take the responsibility of indicating what the copyright status of the data is, namely:

* Is the data a work of the fed govt and in the public domain.
* Is it (or any part of it) copyrighted? By who?
* And if so, are any copyright licenses applied to it? are any of those licenses 'certified' open licenses?

The memorandum should also have addressed the "poison pill" problem of copyright works appearing within government data.

Ideas here are riffed from James Jacobs, see this email: https://groups.google.com/d/msg/openhouseproject/x65WlQ_PLfU/v_hHoGAj0-8J

**Comment by gbinal** [comment]
It looks like this has been covered by the v1.1 updates as well as recent guidance from OMB to agencies.  I think we can close this.
